export const Emoji = {
  // ===== Status & Feedback =====
  SUCCESS: "✅",
  ERROR: "❌",
  WARN: "⚠️",
  INFO: "ℹ️",
  DEBUG: "🐛",
  LOADING: "⏳",
  HOURGLASS: "⌛",
  DONE: "✓",
  SKIP: "⊘",
  QUESTION: "❓",
  EXCLAIM: "❗",
  NEW: "🆕",
  OK: "🆗",

  // ===== Actions & Arrows =====
  ARROW_RIGHT: "→",
  ARROW_LEFT: "←",
  ARROW_UP: "↑",
  ARROW_DOWN: "↓",
  CHECK: "✔",
  CROSS: "✗",
  REFRESH: "🔄",
  SYNC: "🔃",
  RETRY: "↩️",

  // ===== Media Controls =====
  PLAY: "▶️",
  PAUSE: "⏸",
  STOP: "⏹",
  RECORD: "⏺",
  FAST_FORWARD: "⏩",
  REWIND: "⏪",
  EJECT: "⏏️",

  // ===== Trend / Data =====
  UP_TREND: "📈",
  DOWN_TREND: "📉",
  CHART: "📊",
  STAR: "⭐",
  SPARKLES: "✨",
  FIRE: "🔥",
  HEART: "❤️",
  ROCKET: "🚀",
  GEAR: "⚙️",
  ZAP: "⚡",
  BOOM: "💥",
  TARGET: "🎯",
  TROPHY: "🏆",
  MEDAL: "🏅",

  // ===== File / Data / Storage =====
  FILE: "📄",
  FILES: "🗂️",
  FOLDER: "📁",
  FOLDER_OPEN: "📂",
  TRASH: "🗑️",
  SAVE: "💾",
  DATABASE: "🗄️",
  ARCHIVE: "📦",
  CLIPBOARD: "📋",
  PIN: "📌",
  PAPERCLIP: "📎",
  BOOKMARK: "🔖",

  // ===== Security =====
  LOCK: "🔒",
  UNLOCK: "🔓",
  KEY: "🔑",
  SHIELD: "🛡️",
  FINGERPRINT: "👆",
  EYE: "👁️",

  // ===== Development =====
  BUG: "🐛",
  LINK: "🔗",
  CHAIN_BREAK: "⛓️‍💥",
  CODE: "💻",
  TERMINAL: "🖥️",
  PACKAGE: "📦",
  WRENCH: "🔧",
  HAMMER: "🔨",
  TOOLS: "🛠️",
  TEST_TUBE: "🧪",
  MAGNIFYING_GLASS: "🔍",
  BRANCH: "🌿",
  MERGE: "🔀",
  TAG: "🏷️",

  // ===== Network / Cloud =====
  GLOBE: "🌐",
  CLOUD: "☁️",
  SATELLITE: "📡",
  SIGNAL: "📶",
  WIFI: "📶",
  PLUG: "🔌",
  BATTERY: "🔋",
  ELECTRIC: "🔌",

  // ===== Communication =====
  MAIL: "📧",
  INBOX: "📥",
  OUTBOX: "📤",
  BELL: "🔔",
  BELL_MUTE: "🔕",
  SPEECH: "💬",
  MEGAPHONE: "📢",
  PHONE: "📞",

  // ===== Time =====
  CLOCK: "🕐",
  ALARM: "⏰",
  STOPWATCH: "⏱️",
  TIMER: "⏲️",
  CALENDAR: "📅",
  DATE: "📆",

  // ===== People / Reactions =====
  THUMBS_UP: "👍",
  THUMBS_DOWN: "👎",
  CLAP: "👏",
  WAVE: "👋",
  RAISED_HANDS: "🙌",
  PRAY: "🙏",
  MUSCLE: "💪",
  BRAIN: "🧠",
  EYES: "👀",
  THINKING: "🤔",
  SHRUG: "🤷",
  FACEPALM: "🤦",

  // ===== Weather / Nature =====
  SUN: "☀️",
  MOON: "🌙",
  STAR_NIGHT: "🌟",
  RAIN: "🌧️",
  SNOW: "❄️",
  STORM: "⛈️",
  RAINBOW: "🌈",
  LEAF: "🍃",
  TREE: "🌳",
  SEEDLING: "🌱",

  // ===== Numbers / Symbols =====
  HUNDRED: "💯",
  INFINITY: "♾️",
  PLUS: "➕",
  MINUS: "➖",
  MULTIPLY: "✖️",
  DIVIDE: "➗",
  RECYCLE: "♻️",

  // ===== Misc =====
  PARTY: "🎉",
  CONFETTI: "🎊",
  GIFT: "🎁",
  FLAG: "🚩",
  CHECKERED_FLAG: "🏁",
  MAP: "🗺️",
  COMPASS: "🧭",
  LIGHT_BULB: "💡",
  MAGIC: "🪄",
  CRYSTAL_BALL: "🔮",
  ALIEN: "👽",
  ROBOT: "🤖",
  GHOST: "👻",
  SKULL: "💀",
} as const;
